In [1]:
import numpy as np
import torch
import torch.nn as nn
import torch.nn.functional as F
import pandas as pd
from sklearn.model_selection import train_test_split

from helpers import *

In [2]:
class LinearGreaterThanZero(nn.Linear):
    def __init__(self, in_features, bias=False, min_w=0.0000001):
        super().__init__(in_features, 1, bias)
        self.is_bias = bias
        self.min_w = min_w
        if bias:
            nn.init.uniform_(self.bias, self.min_w, 1.0)
        else:
            self.bias = None

    def reset_parameters(self):
        nn.init.uniform_(self.weight, 0.1, 1.0)

    def w(self):
        with torch.no_grad():
            self.weight.data[self.weight.data < 0] = self.min_w
        return self.weight

    def forward(self, input):
        return F.linear(input, self.w(), self.bias)

In [3]:
class LinearInteraction(nn.Linear):
    def __init__(self, in_features, criterion_layer):
        super().__init__(((in_features - 1) * in_features) // 2, 1, False)
        self.in_features = in_features
        self.criterion_layer = criterion_layer

    def reset_parameters(self):
        nn.init.normal_(self.weight, 0.0, 0.1)

    def w(self):
        with torch.no_grad():
            w_i = 0
            w = self.criterion_layer.w()
            for i in range(self.in_features):
                for j in range(i + 1, self.in_features):
                    self.weight.data[:, w_i] = torch.max(
                        self.weight.data[:, w_i], -w[:, i]
                    )
                    self.weight.data[:, w_i] = torch.max(
                        self.weight.data[:, w_i], -w[:, j]
                    )
                    w_i += 1
        return self.weight

    def forward(self, input):
        return F.linear(input, self.w(), None)

In [4]:
class ThresholdLayer(nn.Module):
    def __init__(self, threshold=None, requires_grad=True):
        super().__init__()
        if threshold is None:
            self.threshold = nn.Parameter(
                torch.FloatTensor(1).uniform_(0.1, 0.5), requires_grad=requires_grad
            )
        else:
            self.threshold = nn.Parameter(
                torch.FloatTensor([threshold]), requires_grad=requires_grad
            )

    def forward(self, x):
        return x - self.threshold

In [5]:
class ChoquetConstrained(nn.Module):
    def __init__(self, criteria_nr, **kwargs):
        super().__init__()
        self.criteria_nr = criteria_nr
        self.criteria_layer = LinearGreaterThanZero(criteria_nr)
        self.interaction_layer = LinearInteraction(criteria_nr, self.criteria_layer)
        self.thresholdLayer = ThresholdLayer()

    def forward(self, x):
        if len(x.shape) == 3:
            x = x[:, 0, :]
        x_wi = self.criteria_layer(x[:, : self.criteria_nr])
        x_wij = self.interaction_layer(x[:, self.criteria_nr :])
        weight_sum = self.criteria_layer.w().sum() + self.interaction_layer.w().sum()
        score = (x_wi + x_wij) / (weight_sum)
        return self.thresholdLayer(score)

In [6]:
def mobious_transform(row):
    return list(row) + [
        min(row[i], row[j]) for i in range(len(row)) for j in range(i + 1, len(row))
    ]

In [ ]:
from numpy._typing import NDArray
from typing import ClassVar
from sklearn.preprocessing import OneHotEncoder
from dataclasses import dataclass
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
from scipy import stats

from pandas import DataFrame

@dataclass
class Dataset(object):
  train: DataFrame
  test: DataFrame
  _encoder: ClassVar[OneHotEncoder] = OneHotEncoder(handle_unknown='ignore')

  @classmethod
  def load(cls):
    return cls(
      pd.read_csv(f"./resources/datasets/loan_sanction_train.csv"),
      pd.read_csv(f"./resources/datasets/loan_sanction_test.csv")
    )

  def preprocess(self, split: str) -> tuple[NDArray, NDArray | None]:
    if split == 'train':
      df = self.train.copy()
      df.dropna(inplace=True)
      df.drop(columns=["Loan_ID"], inplace=True)

      X = df.drop(columns=["Loan_Status"])
      y = df["Loan_Status"]

      X = self._encoder.fit_transform(X)
      y = y.map({"N": 0, "Y": 1})

      return X, y
    df = self.test.copy()
    df.dropna(inplace=True)

    df.drop(columns=["Loan_ID"], inplace=True)
    X = self._encoder.transform(df)

    return X


In [7]:
X, y = Dataset.load().preprocess('train')

X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=1234)

In [8]:
train_dataloader = CreateDataLoader(X_train, y_train)
test_dataloader = CreateDataLoader(X_test, y_test)

In [9]:
PATH = "choquet.pt"

In [10]:
model = ChoquetConstrained(criteria_nr)


In [11]:
acc, acc_test, auc, auc_test = Train(model, train_dataloader, test_dataloader, PATH)

print("Accuracy train:\t%.2f%%" % (acc * 100.0))
print("AUC train: \t%.2f%%" % (acc_test * 100.0))
print()
print("Accuracy test:\t%.2f%%" % (auc * 100.0))
print("AUC test: \t%.2f%%" % (auc_test * 100.0))


100%|██████████| 200/200 [00:10<00:00, 19.76it/s]

Accuracy train:	80.38%
AUC train: 	81.00%

Accuracy test:	79.95%
AUC test: 	81.13%


In [12]:
checkpoint = torch.load(PATH)
model.load_state_dict(checkpoint["model_state_dict"])

<All keys matched successfully>

In [13]:
weights = model.criteria_layer.w().detach().numpy()[0]
interaction_weights = model.interaction_layer.w().detach().numpy()[0]
s = weights.sum() + interaction_weights.sum()
weights = weights / s
interaction_weights = interaction_weights / s

interactions = np.zeros((criteria_nr, criteria_nr))
weight_id = 0
for i in range(criteria_nr):
    for j in range(i + 1, criteria_nr):
        interactions[i, j] = interactions[j, i] = interaction_weights[weight_id]
        weight_id += 1

In [14]:
print("Criteria weights:")
print(weights)
print()
print("Criteria interactions:")
print(interactions)

Criteria weights:
[0.18973008 0.13305973 0.21117473 0.1774406 ]

Criteria interactions:
[[0.         0.05106746 0.02530925 0.1322839 ]
 [0.05106746 0.         0.00588444 0.04943791]
 [0.02530925 0.00588444 0.         0.02461192]
 [0.1322839  0.04943791 0.02461192 0.        ]]


In [15]:
shapley = weights + interactions.sum(0) / 2
print("Importance of criterina (Shapley value):")
print(shapley)

Importance of criterina (Shapley value):
[0.29406038 0.18625463 0.23907753 0.28060746]
